IGN:
  ADMINEXPRESS:
    documentation: https://geoservices.ign.fr/documentation/donnees/vecteur/adminexpress
    metadata: https://geoservices.ign.fr/sites/default/files/2021-11/IGNF_ADMIN_EXPRESS_3-1.html

Insee:
  COG:
    2022:
      file: https://www.insee.fr/fr/statistiques/fichier/6051727/commune_2022.csv
      documentation: https://www.insee.fr/fr/information/6051727
    2021:
      file: https://www.insee.fr/fr/statistiques/fichier/5057840/commune2021-csv.zip
      documentation: https://www.insee.fr/fr/information/5057840