IGN:
  ADMINEXPRESS:
    documentation: https://geoservices.ign.fr/documentation/donnees/vecteur/adminexpress
    metadata: https://geoservices.ign.fr/sites/default/files/2021-11/IGNF_ADMIN_EXPRESS_3-1.html
    EXPRESS-COG:
      2022:
        file: https://wxs.ign.fr/x02uy2aiwjo9bm8ce5plwqmr/telechargement/prepackage/ADMINEXPRESS-COG_SHP_TERRITOIRES_PACK_2022-04-15$ADMIN-EXPRESS-COG_3-1__SHP__FRA_L93_2022-04-15/file/ADMIN-EXPRESS-COG_3-1__SHP__FRA_L93_2022-04-15.7z
      field:
        prefix: ADECOG_3-1_SHP_
        metropole: LAMB93_FR
        guadeloupe: RGAF09UTM20_D971
        martinique: RGAF09UTM20_D972
        guyane: UTM22RGFG95_D973
        reunion: RGR92UTM40S_D974
        st-pierre-miquelon: 
        mayotte: RGM04UTM38S_D976
      FTP:
        hostname: "ftp3.ign.fr"
        username: "Admin_Express_ext"
        pwd: "Dahnoh0eigheeFok"      
      2021:
        file: ADMIN-EXPRESS-COG_3-0__SHP__FRA_L93_2021-05-19.7z
      2020:
        file: ADMIN-EXPRESS-COG_2-1__SHP__FRA_L93_2020-11-20.7z
      2019:
        file: ADMIN-EXPRESS-COG_2-0__SHP__FRA_WGS84G_2019-09-24.7z.001


Insee:
  COG:
    2022:
      id: 6051727
      file: https://www.insee.fr/fr/statistiques/fichier/6051727/commune_2022.csv
      documentation: https://www.insee.fr/fr/information/6051727
    2021:
      id: 5057840
      file: https://www.insee.fr/fr/statistiques/fichier/5057840/commune2021-csv.zip
      documentation: https://www.insee.fr/fr/information/5057840
      
      
Services comparables :
  Nom : "NUTS Converter"
  Nature : service web
  Producteur : Commission européenne
  Service rendu : "Convertit la nomenclature des NUTS entre Etats et entre niveaux (ex : à quel découpage administratif polonais correspondent les départements français ?)"
  URL : https://urban.jrc.ec.europa.eu/nutsconverter/#/
