IGN:
  ADMINEXPRESS:
    documentation: https://geoservices.ign.fr/documentation/donnees/vecteur/adminexpress
    metadata: https://geoservices.ign.fr/sites/default/files/2021-11/IGNF_ADMIN_EXPRESS_3-1.html
    EXPRESS-COG-TERRITOIRE:
      field:
        metropole: LAMB93_FXX
        guadeloupe: RGAF09UTM20_GLP
        martinique: RGAF09UTM20_MTQ
        guyane: UTM22RGFG95_GUF
        reunion: RGR92UTM40S_REU
        st-pierre-miquelon: 
        mayotte: RGM04UTM38S_MYT
      2022:
        prefix: ADMIN-EXPRESS-COG
        date: "2022-04-15"
        version: "3-1"
        url_prefix: https://wxs.ign.fr/x02uy2aiwjo9bm8ce5plwqmr/telechargement/prepackage/ADMINEXPRESS-COG_SHP_TERRITOIRES_PACK
        structure: "{url_prefix}_{date}${prefix}_{version}__SHP_{field}_{date}/file/{prefix}_{version}__SHP_{field}_{date}.7z"
      2021:
        prefix: ADMIN-EXPRESS-COG
        date: "2021-05-19"
        version: "3-0"
        url_prefix: https://wxs.ign.fr/x02uy2aiwjo9bm8ce5plwqmr/telechargement/prepackage/ADMINEXPRESS-COG_SHP_TERRITOIRES_PACK
        structure: "{url_prefix}_{date}${prefix}_{version}__SHP_{field}_{date}/file/{prefix}_{version}__SHP_{field}_{date}.7z"
      2020:
        prefix: ADMIN-EXPRESS-COG
        date: "2020-11-20"
        version: "2-1"
        url_prefix: https://wxs.ign.fr/x02uy2aiwjo9bm8ce5plwqmr/telechargement/prepackage/ADMINEXPRESS-COG_SHP_TERRITOIRES_PACK_11-2020
        structure: "{url_prefix}${prefix}_{version}__SHP__FRA_{date}/file/{prefix}_{version}__SHP__FRA_{date}.7z"
      2019:
        prefix: ADMIN-EXPRESS-COG
        date: "2019-09-24"
        version: "2-0"
        url_prefix: https://wxs.ign.fr/x02uy2aiwjo9bm8ce5plwqmr/telechargement/prepackage/ADMINEXPRESS-COG_SHP_TERRITOIRES_PACK_09-2019
        structure: "{url_prefix}${prefix}_{version}__SHP__FRA_{date}/file/{prefix}_{version}__SHP__FRA_{date}.7z"
    EXPRESS-COG:
      field:
        prefix: ADECOG_3-1_SHP_
        metropole: LAMB93_FR
        guadeloupe: RGAF09UTM20_D971
        martinique: RGAF09UTM20_D972
        guyane: UTM22RGFG95_D973
        reunion: RGR92UTM40S_D974
        st-pierre-miquelon: 
        mayotte: RGM04UTM38S_D976
      FTP:
        hostname: "ftp3.ign.fr"
        username: "Admin_Express_ext"
        pwd: "Dahnoh0eigheeFok"      
      2022:              
        file: https://wxs.ign.fr/x02uy2aiwjo9bm8ce5plwqmr/telechargement/prepackage/ADMINEXPRESS_SHP_WGS84G_PACK_2022-06-21$ADMIN-EXPRESS_3-1__SHP__FRA_WM_2022-06-21/file/ADMIN-EXPRESS_3-1__SHP__FRA_WM_2022-06-21.7z
      2021:
        file: https://wxs.ign.fr/x02uy2aiwjo9bm8ce5plwqmr/telechargement/prepackage/ADMINEXPRESS-COG_SHP_WGS84G_PACK_2021-05-19$ADMIN-EXPRESS-COG_3-0__SHP_WGS84G_FRA_2021-05-19/file/ADMIN-EXPRESS-COG_3-0__SHP_WGS84G_FRA_2021-05-19.7z
      2020:
        file: https://wxs.ign.fr/x02uy2aiwjo9bm8ce5plwqmr/telechargement/prepackage/ADMINEXPRESS-COG_SHP_WGS84G_PACK_11-2020$ADMIN-EXPRESS-COG_2-1__SHP__FRA_2020-11-20/file/ADMIN-EXPRESS-COG_2-1__SHP__FRA_2020-11-20.7z
      2019:
        file: https://wxs.ign.fr/x02uy2aiwjo9bm8ce5plwqmr/telechargement/prepackage/ADMINEXPRESS-COG_SHP_WGS84G_PACK_09-2019$ADMIN-EXPRESS-COG_2-0__SHP__FRA_2019-09-24/file/ADMIN-EXPRESS-COG_2-0__SHP__FRA_2019-09-24.7z
      2018:
        file: https://wxs.ign.fr/x02uy2aiwjo9bm8ce5plwqmr/telechargement/prepackage/ADMINEXPRESS-COG-PACK_2018-04-01$ADMIN-EXPRESS-COG_1-1__SHP__FRA_2018-04-03/file/ADMIN-EXPRESS-COG_1-1__SHP__FRA_2018-04-03.7z
      2017:
        file: https://wxs.ign.fr/x02uy2aiwjo9bm8ce5plwqmr/telechargement/prepackage/ADMINEXPRESS-COG-PACK_2017-07-07$ADMIN-EXPRESS-COG_1-0__SHP__FRA_2017-06-19/file/ADMIN-EXPRESS-COG_1-0__SHP__FRA_2017-06-19.7z
    EXPRESS-COG-CARTO-TERRITOIRE:
      field:
        metropole: LAMB93_FXX
        guadeloupe: RGAF09UTM20_GLP
        martinique: RGAF09UTM20_MTQ
        guyane: UTM22RGFG95_GUF
        reunion: RGR92UTM40S_REU
        st-pierre-miquelon: 
        mayotte: RGM04UTM38S_MYT
      2022:
        prefix: ADMINEXPRESS-COG-CARTO
        date: "2022-04-15"
        version: "3-1"
        url_prefix: https://wxs.ign.fr/x02uy2aiwjo9bm8ce5plwqmr/telechargement/prepackage/ADMINEXPRESS-COG-CARTO_SHP_TERRITOIRES_PACK_2022-04-15
        structure: "{url_prefix}_{date}${prefix}_{version}__SHP_{field}_{date}/file/{prefix}_{version}__SHP_{field}_{date}.7z"
      2021:
        prefix: ADMINEXPRESS-COG-CARTO
        date: "2021-05-19"
        version: "3-0"
        url_prefix: https://wxs.ign.fr/x02uy2aiwjo9bm8ce5plwqmr/telechargement/prepackage/ADMINEXPRESS-COG-CARTO_SHP_TERRITOIRES_PACK_2021-05-19
        structure: "{url_prefix}_{date}${prefix}_{version}__SHP_{field}_{date}/file/{prefix}_{version}__SHP_{field}_{date}.7z"
    EXPRESS-COG-CARTO:
      2022:
        file: https://wxs.ign.fr/x02uy2aiwjo9bm8ce5plwqmr/telechargement/prepackage/ADMINEXPRESS-COG-CARTO_SHP_WGS84G_PACK_2022-04-15$ADMIN-EXPRESS-COG-CARTO_3-1__SHP_WGS84G_FRA_2022-04-15/file/ADMIN-EXPRESS-COG-CARTO_3-1__SHP_WGS84G_FRA_2022-04-15.7z
      2021:
        file: https://wxs.ign.fr/x02uy2aiwjo9bm8ce5plwqmr/telechargement/prepackage/ADMINEXPRESS-COG-CARTO_SHP_WGS84G_PACK_2021-05-19$ADMIN-EXPRESS-COG-CARTO_3-0__SHP_WGS84G_FRA_2021-05-19/file/ADMIN-EXPRESS-COG-CARTO_3-0__SHP_WGS84G_FRA_2021-05-19.7z
  BDTOPO:
    documentation: https://geoservices.ign.fr/documentation/donnees/vecteur/bdtopo
    metadata: https://geoservices.ign.fr/sites/default/files/2023-01/IGNF_BDTOPOr_3-3.html
    REMOVE:
      field:
        france_entiere: WGS84G_FRA
      2018:
          prefix: BDTOPO
          year: "18"
          date: "2018-01-01"
          version: "2-2"
          france_entiere: WGS84G_FRA
          url_prefix: https://wxs.ign.fr/859x8t863h6a09o9o6fy4v60/telechargement/inspire/BDTOPO-FRANCE-ADMIN-SSDOUBLON-PACK
          structure: "{url_prefix}_{year}.1${prefix}_{version}_ADMINISTRATIF_SHP_{france_entiere}_{date}/file/{prefix}_{version}_ADMINISTRATIF_SHP_{france_entiere}_{date}.7z"
      2017:
          prefix: BDTOPO
          year: "17"
          date: "2017-01-01"
          version: "2-2"
          france_entiere: WGS84G_FRA
          url_prefix: https://wxs.ign.fr/859x8t863h6a09o9o6fy4v60/telechargement/inspire/BDTOPO-FRANCE-ADMIN-SSDOUBLON-PACK
          structure: "{url_prefix}_{year}.1${prefix}_{version}_ADMINISTRATIF_SHP_{france_entiere}_{date}/file/{prefix}_{version}_ADMINISTRATIF_SHP_{france_entiere}_{date}.7z"
      2016:
          prefix: BDTOPO
          year: "16"
          date: "2016-01-01"
          version: "2-1"
          france_entiere: WGS84G_FRA
          url_prefix: https://wxs.ign.fr/859x8t863h6a09o9o6fy4v60/telechargement/inspire/BDTOPO-FRANCE-ADMIN-SSDOUBLON-PACK
          structure: "{url_prefix}_{year}.1${prefix}_{version}_ADMINISTRATIF_SHP_{france_entiere}_{date}/file/{prefix}_{version}_ADMINISTRATIF_SHP_{france_entiere}_{date}.7z"
      2015:
          prefix: BDTOPO
          year: "15"
          date: "2015-01-01"
          version: "2-1"
          france_entiere: WGS84G_FRA
          url_prefix: https://wxs.ign.fr/859x8t863h6a09o9o6fy4v60/telechargement/inspire/BDTOPO-FRANCE-ADMIN-SSDOUBLON-PACK
          structure: "{url_prefix}_{year}.1${prefix}_{version}_ADMINISTRATIF_SHP_{france_entiere}_{date}/file/{prefix}_{version}_ADMINISTRATIF_SHP_{france_entiere}_{date}.7z"
      2014:
          prefix: BDTOPO
          year: "14"
          date: "2014-01-01"
          version: "2-1"
          france_entiere: WGS84G_FRA
          url_prefix: https://wxs.ign.fr/859x8t863h6a09o9o6fy4v60/telechargement/inspire/BDTOPO-FRANCE-ADMIN-SSDOUBLON-PACK
          structure: "{url_prefix}_{year}.1${prefix}_{version}_ADMINISTRATIF_SHP_{france_entiere}_{date}/file/{prefix}_{version}_ADMINISTRATIF_SHP_{france_entiere}_{date}.7z"
      2013:
          prefix: BDTOPO
          year: "13"
          date: "2013-01-01"
          version: "2-1"
          france_entiere: WGS84G_FRA
          url_prefix: https://wxs.ign.fr/859x8t863h6a09o9o6fy4v60/telechargement/inspire/BDTOPO-FRANCE-ADMIN-SSDOUBLON-PACK
          structure: "{url_prefix}_{year}.1${prefix}_{version}_ADMINISTRATIF_SHP_{france_entiere}_{date}/file/{prefix}_{version}_ADMINISTRATIF_SHP_{france_entiere}_{date}.7z"
      2011:
          prefix: BDTOPO
          year: "11"
          date: "2011-01-01"
          version: "2-0"
          france_entiere: WGS84G_FRA
          url_prefix: https://wxs.ign.fr/859x8t863h6a09o9o6fy4v60/telechargement/inspire/BDTOPO-FRANCE-ADMIN-SSDOUBLON-PACK
          structure: "{url_prefix}_{year}.1${prefix}_{version}_ADMINISTRATIF_SHP_{france_entiere}_{date}/file/{prefix}_{version}_ADMINISTRATIF_SHP_{france_entiere}_{date}.7z"
      2010:
          prefix: BDTOPO
          year: "10"
          date: "2010-01-01"
          version: "2-0"
          france_entiere: WGS84G_FRA
          url_prefix: https://wxs.ign.fr/859x8t863h6a09o9o6fy4v60/telechargement/inspire/BDTOPO-FRANCE-ADMIN-SSDOUBLON-PACK
          structure: "{url_prefix}_{year}.1${prefix}_{version}_ADMINISTRATIF_SHP_{france_entiere}_{date}/file/{prefix}_{version}_ADMINISTRATIF_SHP_{france_entiere}_{date}.7z"
      2009:
          prefix: BDTOPO
          year: "09"
          date: "2009-01-01"
          version: "2-0"
          france_entiere: WGS84G_FRA
          url_prefix: https://wxs.ign.fr/859x8t863h6a09o9o6fy4v60/telechargement/inspire/BDTOPO-FRANCE-ADMIN-SSDOUBLON-PACK
          structure: "{url_prefix}_{year}.1${prefix}_{version}_ADMINISTRATIF_SHP_{france_entiere}_{date}/file/{prefix}_{version}_ADMINISTRATIF_SHP_{france_entiere}_{date}.7z"
  CONTOUR-IRIS: #variables INSEE_COM NOM_COM IRIS CODE_IRIS NOM_IRIS TYP_IRIS ; manque la var Grand-Quartier (GRD_QUART) présente sur les tables insee https://www.insee.fr/fr/information/2017499
    documentation: https://geoservices.ign.fr/documentation/donnees/vecteur/contoursiris
    metadata: https://geoservices.ign.fr/sites/default/files/2022-03/IGNF_Contours-IRISr_2-1.html
    field:
      prefix: CONTOURS-IRIS_2-1_SHP_
      metropole: LAMB93_FXX-
      guadeloupe: RGAF09UTM20_GLP-
      martinique: RGAF09UTM20_MTQ-
      guyane: UTM22RGFG95_GUF-
      reunion: RGR92UTM40S_REU-
      mayotte: RGM04UTM38S_MYT-
      suffix: $ANNEE # les noms de fichiers comportent le millésime à la fin du moins en 2022 et 2021, faudrait donc un paramètre...vive l'ign...   
    FTP:
      hostname: "ftp3.ign.fr"
      username: "Contours_IRIS_ext"
      pwd: "ao6Phu5ohJ4jaeji"
    2022: #absence du fichier sur le FTP verifiee
      file: https://wxs.ign.fr/1yhlj2ehpqf3q6dt6a2y7b64/telechargement/inspire/CONTOURS-IRIS-PACK_2022-01$CONTOURS-IRIS_2-1__SHP__FRA_2022-01-01/file/CONTOURS-IRIS_2-1__SHP__FRA_2022-01-01.7z
    2021:
      file: CONTOURS-IRIS_2-1__SHP__FRA_2021-01-01.7z
    2020:
      file: CONTOURS-IRIS_2-1__SHP__FRA_2020-01-01.7z
    2019:
      file: CONTOURS-IRIS_2-1__SHP__FRA_2019-01-01.7z.001
    2018:
      file: CONTOURS-IRIS_2-1__SHP__FRA_2018-01-01.7z.001
    2017:
      file: CONTOURS-IRIS_2-1__SHP__FRA_2017-01-01.7z
    2016: #absence sur le FTP verifiee 
      file: https://wxs.ign.fr/1yhlj2ehpqf3q6dt6a2y7b64/telechargement/inspire/CONTOURS-IRIS-2017-06-30%24CONTOURS-IRIS_2-1__SHP__FRA_2017-06-30/file/CONTOURS-IRIS_2-1__SHP__FRA_2017-06-30.7z
    2015: #absence sur le FTP verifiee 
      file: https://wxs.ign.fr/1yhlj2ehpqf3q6dt6a2y7b64/telechargement/inspire/CONTOURS-IRIS-2015-01-01%24CONTOURS-IRIS_2-1__SHP_LAMB93_FXX_2016-11-10/file/CONTOURS-IRIS_2-1__SHP_LAMB93_FXX_2016-11-10.7z
    2014: #absence sur le FTP verifiee
      file: https://wxs.ign.fr/1yhlj2ehpqf3q6dt6a2y7b64/telechargement/inspire/CONTOURS-IRIS-2014-01-01%24CONTOURS-IRIS_2-0__SHP_LAMB93_FXX_2014-01-01/file/CONTOURS-IRIS_2-0__SHP_LAMB93_FXX_2014-01-01.7z
    2013:
      file: CONTOURS-IRIS_1-0__SHP_LAMB93_FXX_2013-01-01.7z.001
    2009:
      file: CONTOURS-IRIS_1-0__SHP_LAMB93_FRA_2009-01-01.7z 


Insee:
  COG: #Penser à filtrer sur TYPECOM=COM pour les communes (sans les déléguées) et TYPECOM=ARM pour les arrondissements municipaux PLM
    structure: https://www.insee.fr/fr/statistiques/fichier/{id}/{filename}
    COMMUNE:
        2022:
            id: 6051727
            filename: commune_2022.csv
    CANTON:
        2022:
            id: 6051727
            filename: canton_2022.csv
    ARRONDISSEMENT:
        2022:
            id: 6051727
            filename: arrondissement_2022.csv
    DEPARTEMENT:
        2022:
            id: 6051727
            filename: departement_2022.csv
    REGION:
        2022:
            id: 6051727
            filename: region_2022.csv
    COLLECTIVITE:
        2022:
            id: 6051727
            filename: CTCD_2022.csv
    PAYS:
        2022:
            id: 6051727
            filename: pays_2022.csv