name: Test Python package

on: [push]

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Add libmagic for python-magic on linux
      run: sudo apt-get install libmagic1
    - name: Install dependencies
      run: |
        pip install uv
        uv pip install -r pyproject.toml --system
    - name: Test import
      run: |
        export AWS_ACCESS_KEY_ID=${{ secrets.S3_ACCESS_KEY }}
        export AWS_SECRET_ACCESS_KEY=${{ secrets.S3_SECRET_KEY }}
        # python example/download.py
    - name: Test with pytest
      run: |
        uv run pytest

