name: Test Python package

on: [push]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v5
      with:
        python-version: "3.10"
    - uses: actions/setup-node@v4
      with:
        node-version: "22"
    - name: Install mapshaper
      run: npm install -g mapshaper@0.6.59
    - name: Test the pipeline (no S3)
      run: uv run pytest tests

  client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python-package/cartiflette
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v5
      with:
        python-version: "3.10"
    - name: Test the client
      run: uv run pytest tests
