name: Lint Python package

on: [push]

jobs:
  lint-checking:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Add libmagic for python-magic on linux
      run: sudo apt-get install libmagic1
    - name: Install dependencies
      run: |
        pip install uv
        uv pip install -r pyproject.toml --system
    - name: Lint with flake8
      run: |
        cd cartiflette
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Lint with pylint
      run: |
        pip install pylint
        pylint cartiflette --fail-under=5
#    - name: Test with pytest
#      run: |
#        conda install pytest
#        pytest
